name: jimjaew_app
description: "Rewear Application"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.7

dependencies:
  http: ^1.6.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo_jimjaew.png
