name: jimjaew_app
description: "Rewear Application"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.7

dependencies:
  http: ^1.6.0
  path: ^1.9.0
  font_awesome_flutter: ^10.7.0
  flutter_svg: ^2.0.10
  cloud_firestore: ^6.1.3
  firebase_core: ^4.5.0
  image_picker: ^1.2.1
  path_provider: ^2.1.5
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/iconlogojimjaew.png"